services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    ports:
      - "8000"
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.medic-assistant.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.medic-assistant.tls=true
      - traefik.http.routers.medic-assistant.entrypoints=web,websecure
      - traefik.http.routers.medic-assistant.tls.certresolver=http_resolver
      - traefik.http.middlewares.medic-assistant.headers.SSLRedirect=true
      - traefik.http.middlewares.medic-assistant.headers.STSSeconds=315360000
      - traefik.http.middlewares.medic-assistant.headers.browserXSSFilter=true
      - traefik.http.middlewares.medic-assistant.headers.contentTypeNosniff=true
      - traefik.http.middlewares.medic-assistant.headers.forceSTSHeader=true
      - traefik.http.middlewares.medic-assistant.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.medic-assistant.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.medic-assistant.headers.STSPreload=true
      - traefik.http.routers.medic-assistant.middlewares=medic-assistant@docker
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
